### Working out the compound lens distance to make the correct tube lens

For two thin lenses if collimated light enters from the left to right it will be focused at the 'back focal length' Given by the following:
$$
bfl = \frac{f_2*(d-f_1)}{d-(f_1+f_2)}
$$

In [10]:
f1=40
f2=-40
d=20
expected=40.
bfl=f2*(d-f1)/(d-(f1+f2))

print('b.f.l:', bfl, 'Matches book?', bfl == expected)


b.f.l: 40.0 Matches book? True


The effective focal length is given by the following:
$$
EFL = bfl + d
$$

This tells us how far apart the lenses will be and where the focus of the overall lens pair is.

In [70]:
f1 = 200
f2 = 200
d = np.linspace(1,201,101)

bfl = f2*(d-f1)/(d-(f1+f2))
efl = bfl+d
desired_efl = t2  # 131.75
closest = efl.flat[np.abs(efl - desired_efl).argmin()]
idx = int(np.where(efl == closest)[0])
opt_d_rough = d[idx]
opt_bfl_rough = bfl[idx]

print('Closest EFL:', np.round(closest,2), 'Separation distance:',
      np.round(opt_d_rough,2), 'Back Focal Length', np.round(opt_bfl_rough,2))
# print('\nSeparation Distances and Back Focal Length and Effective Focal Distance\n',
#       np.column_stack((d, bfl, efl)))


Closest EFL: 132.32 Separation distance: 45.0 Back Focal Length 87.32


Now use the closest point and sample much more finely.

In [71]:
f1 = 200
f2 = 200
d = np.linspace(opt_d_rough-1, opt_d_rough+1, 201)

bfl = f2*(d-f1)/(d-(f1+f2))
efl = bfl+d
desired_efl = t2  # 131.75
closest = efl.flat[np.abs(efl - desired_efl).argmin()]
idx = int(np.where(efl == closest)[0])
opt_d = d[idx]
opt_bfl=bfl[idx]

print('Closest EFL:', np.round(closest,2), 'Separation distance:', np.round(opt_d,2),'Back Focal Length',np.round(opt_bfl,2))
print('\nSeparation Distances and Back Focal Length and Effective Focal Distance\n',
      np.column_stack((d, bfl, efl)))


Closest EFL: 131.75 Separation distance: 44.16 Back Focal Length 87.59

Separation Distances and Back Focal Length and Effective Focal Distance
 [[ 44.          87.64044944 131.64044944]
 [ 44.01        87.63729318 131.64729318]
 [ 44.02        87.63413675 131.65413675]
 [ 44.03        87.63098014 131.66098014]
 [ 44.04        87.62782335 131.66782335]
 [ 44.05        87.62466639 131.67466639]
 [ 44.06        87.62150924 131.68150924]
 [ 44.07        87.61835192 131.68835192]
 [ 44.08        87.61519443 131.69519443]
 [ 44.09        87.61203675 131.70203675]
 [ 44.1         87.6088789  131.7088789 ]
 [ 44.11        87.60572087 131.71572087]
 [ 44.12        87.60256266 131.72256266]
 [ 44.13        87.59940428 131.72940428]
 [ 44.14        87.59624571 131.73624571]
 [ 44.15        87.59308697 131.74308697]
 [ 44.16        87.58992806 131.74992806]
 [ 44.17        87.58676896 131.75676896]
 [ 44.18        87.58360969 131.76360969]
 [ 44.19        87.58045024 131.77045024]
 [ 44.2        

Use our new found knowledge to match the tube lens that is on github (EFL 169)

In [61]:
f1 = 200
f2 = 750
d = np.linspace(0, 200, 101)

bfl = f2*(d-f1)/(d-(f1+f2))
efl = bfl+d
desired_efl = 169
closest = efl.flat[np.abs(efl - desired_efl).argmin()]
idx = int(np.where(efl == closest)[0])
opt_d = d[idx]
opt_bfl = bfl[idx]

print('Closest EFL:', closest, 'Separation distance:',
      opt_d, 'Back Focal Length', opt_bfl)
print('\nSeparation Distances and Back Focal Length and Effective Focal Distance\n',
      np.column_stack((d, bfl, efl)))


Closest EFL: 169.2549019607843 Separation distance: 32.0 Back Focal Length 137.2549019607843

Separation Distances and Back Focal Length and Effective Focal Distance
 [[  0.         157.89473684 157.89473684]
 [  2.         156.64556962 158.64556962]
 [  4.         155.39112051 159.39112051]
 [  6.         154.13135593 160.13135593]
 [  8.         152.86624204 160.86624204]
 [ 10.         151.59574468 161.59574468]
 [ 12.         150.31982942 162.31982942]
 [ 14.         149.03846154 163.03846154]
 [ 16.         147.751606   163.751606  ]
 [ 18.         146.45922747 164.45922747]
 [ 20.         145.16129032 165.16129032]
 [ 22.         143.85775862 165.85775862]
 [ 24.         142.54859611 166.54859611]
 [ 26.         141.23376623 167.23376623]
 [ 28.         139.9132321  167.9132321 ]
 [ 30.         138.58695652 168.58695652]
 [ 32.         137.25490196 169.25490196]
 [ 34.         135.91703057 169.91703057]
 [ 36.         134.57330416 170.57330416]
 [ 38.         133.22368421 171.223

In [62]:
f1 = 200
f2 = 750
d = np.linspace(31, 33, 101)

bfl = f2*(d-f1)/(d-(f1+f2))
efl = bfl+d
desired_efl = 169
closest = efl.flat[np.abs(efl - desired_efl).argmin()]
idx = int(np.where(efl == closest)[0])
opt_d = d[idx]
opt_bfl = bfl[idx]

print('Closest EFL:', closest, 'Separation distance:',
      opt_d, 'Back Focal Length', opt_bfl)
print('\nSeparation Distances and Back Focal Length and Effective Focal Distance\n',
      np.column_stack((d, bfl, efl)))


Closest EFL: 169.0017658583308 Separation distance: 31.24 Back Focal Length 137.7617658583308

Separation Distances and Back Focal Length and Effective Focal Distance
 [[ 31.         137.92165397 168.92165397]
 [ 31.02       137.90833315 168.92833315]
 [ 31.04       137.89501175 168.93501175]
 [ 31.06       137.88168977 168.94168977]
 [ 31.08       137.86836721 168.94836721]
 [ 31.1        137.85504407 168.95504407]
 [ 31.12       137.84172036 168.96172036]
 [ 31.14       137.82839606 168.96839606]
 [ 31.16       137.81507118 168.97507118]
 [ 31.18       137.80174572 168.98174572]
 [ 31.2        137.78841968 168.98841968]
 [ 31.22       137.77509306 168.99509306]
 [ 31.24       137.76176586 169.00176586]
 [ 31.26       137.74843808 169.00843808]
 [ 31.28       137.73510972 169.01510972]
 [ 31.3        137.72178078 169.02178078]
 [ 31.32       137.70845126 169.02845126]
 [ 31.34       137.69512115 169.03512115]
 [ 31.36       137.68179047 169.04179047]
 [ 31.38       137.66845921 169.04

## Ray Transfer Matrices (RTM) (ABCD) Matrices
If there is free space between two plance, the ray transfer matrix is given by:
$$
S = \begin{bmatrix} 1 & d \\ 0 & 1 \end{bmatrix}
$$
where d is the separation distance (measured along the optical axis) between the two reference planes.
$$
\begin{bmatrix}x_2 \\ \theta_2\end{bmatrix} = S\begin{bmatrix} x_1 \\ \theta_1 \end{bmatrix}
$$
and this relates the parameters of the two rays as:
$$
x_2 = x_1 +d\theta_1 \\
\theta_2=\theta_1
$$
Another example is that of a thin lens. Its RTM is:
$$
L = \begin{bmatrix} 1 & 0 \\ -\frac{1}{f} & 1 \end{bmatrix}
$$
where f is the focal length. To describe combinations of optical components, RTM may be multipled to obtain an overall RTM for the compound optical system. For the example of free space of length d followed by a lens of focal length f:
$$
LS = \begin{bmatrix} 1 & 0 \\ -\frac{1}{f} & 1 \end{bmatrix} \begin{bmatrix} 1 & d \\ 0 & 1 \end{bmatrix} = \begin{bmatrix} 1&d\\-\frac{1}{f}&1-\frac{d}{f}\end{bmatrix}
$$
We can do a similar thing for a lens followed by free space:
$$
SL = \begin{bmatrix} 1 & d \\ 0 & 1 \end{bmatrix}\begin{bmatrix} 1 & 0 \\ -\frac{1}{f} & 1 \end{bmatrix} = \begin{bmatrix} 1-\frac{d}{f}&d\\-\frac{1}{f}&1\end{bmatrix}
$$
The matrices must be ordered appropriately, with the last matrix premultiplying the second last, and so on until the first matrix is premultiplied by the second.


Ray Transfer Matrices are only valid at the paraxial approximation:
$$ \theta_1 << \frac{\pi}{2}

The RTM that we want is **LSL** The ray propagates through a lens, and air gap, and a second lens. This should be the two lens system.

$$
\begin{bmatrix}r_2 \\ r_2^\prime \end{bmatrix} = \begin{bmatrix}1 & 0 \\ -\frac{1}{f_2}&1\end{bmatrix}\cdot \begin{bmatrix}1&d\\0&1\end{bmatrix}\cdot \begin{bmatrix}1 & 0 \\ -\frac{1}{f_1}&1\end{bmatrix} \cdot \begin{bmatrix}r_1 \\ r_1^\prime \end{bmatrix} = \begin{bmatrix}1-\frac{d}{f_1}&d\\ \frac{d-f_1-f_2}{f_1f_2}&1-\frac{d}{f_2}\end{bmatrix}\cdot \begin{bmatrix}r_1\\r_1^\prime\end{bmatrix}
$$
$$
T_{LSL}=\begin{bmatrix}1-\frac{d}{f_1}&d\\ \frac{d-f_1-f_2}{f_1f_2}&1-\frac{d}{f_2}\end{bmatrix}
$$ 